// AUTH ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// USER ACTIONS
export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

// FLASH MESSAGES
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";

// PORTAL
export const GET_EVENTS = "GET_EVENTS";
export const COMPLETE_EVENT = "CHECK_OFF_EVENT";
export const MARK_IMPORTANT = "MARK_IMPORTANT";
export const ADD_EVENT = "ADD_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const SEARCH_EVENTS = "SEARCH_EVENTS";
