// AUTH ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// USER ACTIONS
export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

// FLASH MESSAGES
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
